project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Monthly and Annual Energy Consumption Analysis"
  author:
    - Ritayan Patra (rp3247)
    - Zehao Jiang (zj2403)
  repo-url: https://github.com/RITS98/Monthly-and-Annual-Energy-Consumption-Analysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


